### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by VaibhavPaliwal0007** [hash-define-organization/Hacktober-Fest-2021#101]
need to style readmeMD.

**Comment by TheInvincibleLearner** [comment]
I would like to improve the style of README.md. Please assign it to me.

**Comment by VaibhavPaliwal0007** [comment]
okay assigned!!! Do provide the screenshot and do your best.
All the best

**Comment by TheInvincibleLearner** [comment]
> okay assigned!!! Do provide the screenshot and do your best. All the best

Sure I would try my best and provide you with the screenshot as well.

**Comment by MariamChowdhury** [comment]
Hi, I want to work on this. Can you please assign me this issue?

**Comment by VaibhavPaliwal0007** [comment]
Okay, @MariamChowdhury assigned!!
