### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by yogeshwalecha** [hash-define-organization/Hacktober-Fest-2021#111]

**Comment by yogeshwalecha** [comment]
I would like to work on this problem.

**Comment by janhvi06** [comment]
I want to solve this issue. Kindly assign it me.

**Comment by ij007** [comment]
Please provide the description and screenshots of the problem @yogeshwalecha ASAP or else we will close it or assign to to somebody else.

**Comment by Sidarth-Roy** [comment]
I would Like to solve this problem.
