### ISSUE TITLE
Adding Linear Search in C (DSA)

### ISSUE THREAD

**Issue by AnmolManocha** [hash-define-organization/Hacktober-Fest-2021#13]
Hey everyone!
I want to add Linear Search in C language.
Please assign me this.
Thank You!

**Comment by VaibhavPaliwal0007** [comment]
Just check there is no same code for the linear search

**Comment by YushChaudhary** [comment]
is it still available if yes please assign me.

**Comment by VaibhavPaliwal0007** [comment]
This issue is already assigned.

**Comment by YushChaudhary** [comment]
ok can you add more issues .

**Comment by VaibhavPaliwal0007** [comment]
You can also add one of your own. We will see to it if it is relevant.

**Comment by YushChaudhary** [comment]
ok but i don't know how to add label in it.
