### ISSUE TITLE
Adding Kadane's Algorithm

### ISSUE THREAD

**Issue by HarshalRathore** [hash-define-organization/Hacktober-Fest-2021#130]
**Is your feature request related to a problem? Please describe.**
There is no Algorithms folder and there is no kadane's algorithm.

**Describe the solution you'd like**
I would like to contribute my code of kadane's algorithm.

**Describe alternatives you've considered**
_Null_

**Additional context**
_Null_

**Comment by VaibhavPaliwal0007** [comment]
DIgital Ocean is not accepting DSA spam as few repositories have been banned. Kindly choose a different issue or a relevant one.  You can contribute to another departments/
