### ISSUE TITLE
Add some computer networking coding problems .

### ISSUE THREAD

**Issue by AB-Jeet** [hash-define-organization/Hacktober-Fest-2021#138]
Pls assign it to me under hacktoberfest.

**Comment by VaibhavPaliwal0007** [comment]
Please elaborate the issue

**Comment by AB-Jeet** [comment]
coding like error detection such as CRC, LRC, VRC and routing protocol . also OSI model using graphics
![OSI](https://user-images.githubusercontent.com/62722910/135725514-cc24ae6c-9a92-4ab6-9ae6-8264e552ed40.png)

**Comment by VaibhavPaliwal0007** [comment]
Nice Explanation!! Issue assigned @AB-Jeet 
All the best.
