### ISSUE TITLE
DSA [Arrays]- Any base to Any base conversion in C++

### ISSUE THREAD

**Issue by Aryan283** [hash-define-organization/Hacktober-Fest-2021#139]
A Clear and concise explanation of the above problem is provided here -
1. You are given a number n.
2. You are given a base b1. n is a number on base b.
3. You are given another base b2.
4. You are required to convert the number n of base b1 to a number in base b2.

   For eg. The program takes the input from user as 172 in base 8 and if the user wants to convert it to base 2 then the Output 
   should be 1111010

**Comment by VaibhavPaliwal0007** [comment]
Violates digital ocean's tos
