### ISSUE TITLE
Instagram Login Page Clone (HTML-CSS)

### ISSUE THREAD

**Issue by tanishchugh01** [hash-define-organization/Hacktober-Fest-2021#141]
I would like to Instagram-login-page-clone HTML-CSS project.

Here is a link to my repository : https://github.com/tanishchugh01/instagram-login

![image](https://user-images.githubusercontent.com/72879445/135711096-e2954d4e-c433-47c7-9c0f-e1838c0648d7.png)

![instagif](https://user-images.githubusercontent.com/72879445/135711088-23b315e0-8de9-4c89-b522-d60f8748176a.gif)

Please do assign it to me.

**Comment by VaibhavPaliwal0007** [comment]
okay assigned!! @tanishchugh01

**Comment by ij007** [comment]
Please link the PR to the issue !
