### ISSUE TITLE
Survey Form (HTML / CSS)

### ISSUE THREAD

**Issue by ij007** [hash-define-organization/Hacktober-Fest-2021#152]
**Describe the solution you'd like**
I would like to work on a survey form which take various input. Please assign it to me.

**Comment by Amritanshu02** [comment]
Hello, I would like to work upon this task, could you assign it to me

**Comment by WINOFFRG** [comment]
Explain the project/Issue in more detail and make TODO List mentioning your tasks

**Comment by ij007** [comment]
I would like to create a static web page which has several fields like name email which ca be used to take surveys.

**Comment by VaibhavPaliwal0007** [comment]
okay assigned!! @ij007
