### ISSUE TITLE
Want to add some ml algorithms like regression, decision tree, naive bayes

### ISSUE THREAD

**Issue by NightFury-Dracarys** [hash-define-organization/Hacktober-Fest-2021#155]
**I saw a section for AI & Ml and being an enthusiast I would like to propose to add some ideas like some ml algos to the section**

**It would be great if you assign it to me and subsequently accept my pull request**

**Great work on hacktober fest 2021, thanks for the initiative...**

**Comment by ij007** [comment]
Assigned !!

**Comment by NightFury-Dracarys** [comment]
Thanks I have made the pull request,
 You can check it out and accept and merge my pull request.

**Comment by NightFury-Dracarys** [comment]
Please check my pull request...and then accept it so that it gets merge
with the main stream

**Comment by ij007** [comment]
Please mention your PR number.
