### ISSUE TITLE
Cpp questions of patterns, palindrome, factorial...

### ISSUE THREAD

**Issue by NightFury-Dracarys** [hash-define-organization/Hacktober-Fest-2021#156]
**Is your feature request related to a problem? Please describe.**
Cpp questions

**Describe the solution you'd like**
I would like to add some cpp pattern questions ,palindrome,factorial,greatest three,prime....
The pattern ones would include butterfly,rhombus,traingle upper and a suprise one which is a next button like in a music player

**Comment by ij007** [comment]
Digital Ocean is not accepting DSA spam as few repositories have been banned. Kindly choose a different issue or a relevant one. You can however contribute to another department.
