### ISSUE TITLE
Google Clone

### ISSUE THREAD

**Issue by SHIVANGISINGH1** [hash-define-organization/Hacktober-Fest-2021#161]
I would like to add Google Clone made using Html and CSS.

Here is link to my repository https://github.com/SHIVANGISINGH1/firstClone.

![image](https://user-images.githubusercontent.com/80265624/135744249-02e192a3-9d16-4539-84e9-1156ee399410.png)

**Comment by VaibhavPaliwal0007** [comment]
Okay assigned!! @SHIVANGISINGH1

**Comment by VaibhavPaliwal0007** [comment]
Do link the pr to this issue. Take help from @AbhiprayaSinha.
