### ISSUE TITLE
To add animated TOURS AND TRAVEL website using (HTML-CSS).

### ISSUE THREAD

**Issue by sarthakgupta878** [hash-define-organization/Hacktober-Fest-2021#165]
Hey! I would like to add my project named "tours-travels-website" under WebDev/HTML-CSS.
Here's the link to website :
[https://sarthakgupta878.github.io/tours-travel-website/](url)
![tours-travel](https://user-images.githubusercontent.com/79013345/135746018-145b358a-f1fc-40d7-b3ed-0121c98c5259.PNG)
You can assign this to me under hacktober-fest.
Thank You!

**Comment by VaibhavPaliwal0007** [comment]
Ok assigned!! All the Best @sarthakgupta878
