### ISSUE TITLE
Recursion standard questions

### ISSUE THREAD

**Issue by soniyakaramchandani42510** [hash-define-organization/Hacktober-Fest-2021#166]
SOME OF THE STANDARD PROBLEMS OF RECURSION
1)printing number using recursion
2)check if array is sorted or not
3)print all powerset of array/string
4)no of jumps to climb the stairs
5)remove occurrence of pi
6)tower of hanoi
7)remove middle element of stack 
please assign me.

**Comment by VaibhavPaliwal0007** [comment]
Digital Ocean is not accepting DSA spam as few repositories have been banned. Kindly choose a different issue or a relevant one. You can however contribute to another department.
