### ISSUE TITLE
Cpp program to reverse a Singly Linked List

### ISSUE THREAD

**Issue by piyush26arora** [hash-define-organization/Hacktober-Fest-2021#18]

**Comment by VaibhavPaliwal0007** [comment]
need clean code

**Comment by YushChaudhary** [comment]
can you assign this to me. Thanks

**Comment by achitJ** [comment]
> can you assign this to me. Thanks

This issue has already been assigned and closed, please try another issue or make your own, if you wish to as long as it is different from what already is present.
