### ISSUE TITLE
DSA in GOLANG

### ISSUE THREAD

**Issue by sabir-catalogic** [hash-define-organization/Hacktober-Fest-2021#190]
**Is your feature request related to a problem? Please describe.**
I noticed that there are not much DSA related solutions in GOLANG,

**Describe the solution you'd like**
As a GOLANG developer i want to contribute some DS and ALGO implementation in GOLANG.

**Comment by WINOFFRG** [comment]
Need more information, No of Questions and Topics that will be covered. Basic/Beginner questions are no longer accepted.

**Comment by sabir-catalogic** [comment]
Hey @WINOFFRG ,
i was just thinking of covering the topics like 
- Array
- Linked List
- Stack
- Queue
- Binary Tree
- Binary Search Tree
- Heap
- Hashing
- Graph
in GOLANG , because there are not many developers of GOLANG, these basic info is rare, and i was thinking of covering the same. And yes these are the basic concepts , If it is not allowed please let me know. i will then go for some coding Questions

**Comment by VaibhavPaliwal0007** [comment]
LGTM Issue assigned!!

**Comment by VaibhavPaliwal0007** [comment]
okay reviewed!! 
Closing this issue as it has been resolved.
