### ISSUE TITLE
Subset Problem Using Recursion (DSA, C++)

### ISSUE THREAD

**Issue by ayan2809** [hash-define-organization/Hacktober-Fest-2021#207]
**Is your feature request related to a problem? Please describe.**
Yes, I have checked the existing repository and want to add the following code under the Recursion Folder

**Describe the solution you'd like**
A recursive approach towards solving the subset problem of Leetcode

Please Assign it to me

**Comment by WINOFFRG** [comment]
Sorry, Such DSA Questions are no longer accepted.
