### ISSUE TITLE
adding Binary to decimal and decimal to binary conversions in java (DSA)

### ISSUE THREAD

**Issue by RADHIKA-JOSHI123** [hash-define-organization/Hacktober-Fest-2021#21]

**Comment by VaibhavPaliwal0007** [comment]
Kindly do in clean code and make sure the code is unique in the repo

**Comment by RADHIKA-JOSHI123** [comment]
Sure 

thank you for guiding me
Do I need to make above changes now or from next contributions please do guide

**Comment by RADHIKA-JOSHI123** [comment]
Thank you for guiding me
Do I need to make above changes now or from next contributions,please do guide me

Also to get this contribution counted in hacktoberfirst do I need to close this issue.
Because its showing me pull request not accepted in hacktoberfest profile.Please do help me to solve this doubt.

Thanks & Regards

**Comment by VaibhavPaliwal0007** [comment]
Just write resolve issue #issueno in the pr you put to close this issue.

**Comment by RADHIKA-JOSHI123** [comment]
Okay, thanks for guiding :)
