### ISSUE TITLE
Iris Data Set Analysis and by Applying Support Vector Machine find the accuracy of the model

### ISSUE THREAD

**Issue by Parthkh28** [hash-define-organization/Hacktober-Fest-2021#257]
The Iris flower data set is a multivariate data set introduced by the British statistician and biologist Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems. It is sometimes called Anderson's Iris data set because Edgar Anderson collected the data to quantify the morphologic variation of Iris flowers of three related species. The data set consists of 50 samples from each of three species of Iris (Iris Setosa, Iris virginica, and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

**Comment by ij007** [comment]
Assigned!!
