### ISSUE TITLE
Developing Website for Hashdefine

### ISSUE THREAD

**Issue by amittri1025** [hash-define-organization/Hacktober-Fest-2021#27]
## Let's develop a new website for Hashdefine this October
Languages Involved: 
1. HTML
2. CSS
3. JavaScript
(You can use any JS library for effects like AOS Popper )

You can take Inspiration for the Design from above image : https://www.landingfolio.com/inspiration/post/pipe

![ Website Sample ](https://user-images.githubusercontent.com/74503582/135602658-5579791c-3816-4db2-b693-5fc80a9a227a.png)

**Comment by VaibhavPaliwal0007** [comment]
So this website was built by you?

**Comment by VaibhavPaliwal0007** [comment]
Do in the specified folder

**Comment by amittri1025** [comment]
> So this website was built by you?

Nopes , this is the inspiration or Prototype for HOW THE WEBSITE SHOULD LOOK LIKE !!

**Comment by VaibhavPaliwal0007** [comment]
Okay assigned!! Best of luck
