### ISSUE TITLE
Age Calculator

### ISSUE THREAD

**Issue by Shobhit61730** [hash-define-organization/Hacktober-Fest-2021#302]
This is an age calculator . You can calculate your age in days.
In main page you just entered your DOB.
![image](https://user-images.githubusercontent.com/87086265/137244541-50075700-55ee-400b-ad71-00e3ba9461d3.png)

You fill this by filling your DOB.
![image](https://user-images.githubusercontent.com/87086265/137244819-eadb30fb-3cc3-4f60-ac9a-ee6494d9fe41.png)

After that you just click on the calculate age button. 
![image](https://user-images.githubusercontent.com/87086265/137244955-76fad2f4-4080-4054-9713-c1207532ba55.png)

This alert box define how old you are in days. 
Hope, you enjoy it.

**Comment by ij007** [comment]
Assigned !!
