### ISSUE TITLE
My Portfolio by using HTML,CSS.

### ISSUE THREAD

**Issue by Shobhit61730** [hash-define-organization/Hacktober-Fest-2021#303]
This is my portfolio website.
This is my Home page.
![image](https://user-images.githubusercontent.com/87086265/137245953-10c544ea-dd9f-462a-8ee5-18f0a4a72fc2.png)

Next page is About Us Section .Here is my resume.
![image](https://user-images.githubusercontent.com/87086265/137246192-bf71d44c-dd06-43dc-947d-188a8a95dbac.png)

Next section is My interests and skills. You can see my linkedin  profile also.
![image](https://user-images.githubusercontent.com/87086265/137246790-097c3cb2-a201-45ed-9ac3-e5acf4758610.png)

In last section -- here is my projects.
E-commerce website ,Age calculator, Number guess game.
![image](https://user-images.githubusercontent.com/87086265/137246649-3c1dd8cb-edda-4a39-bd4e-8dd22ec6390a.png)

This site is responsible as well as.
![image](https://user-images.githubusercontent.com/87086265/137247162-012ce4e2-8b2e-4463-a79f-78af386578bd.png)

**Comment by ij007** [comment]
Assigned !!
