### ISSUE TITLE
MobileDev Kotlin : Recycler View Implementation App

### ISSUE THREAD

**Issue by shubhmittal07** [hash-define-organization/Hacktober-Fest-2021#307]
This app Covers topics like:
* Implementation of Recycler View
* Using Drawables as Gradient background
* Card View
* ImageView

**ScreenShots** --

<p align = "left">
<img src = "https://user-images.githubusercontent.com/59731205/137309018-7e6d5f01-a346-4099-8d8f-5db28b491810.png" width = "200">
<img src = "https://user-images.githubusercontent.com/59731205/137309085-9b0a27b1-506e-45f5-b383-2e992ce81ade.png" width = "200">
<img src = "https://user-images.githubusercontent.com/59731205/137309178-27987a8a-9677-4b92-ad13-488e5fa483c2.png" width = "200">
<img src = "https://user-images.githubusercontent.com/59731205/137309246-c0e606a7-9aa9-42c1-97f8-c62d05a7f183.png" width = "200">
</p>

**Comment by VaibhavPaliwal0007** [comment]
okay assigned!!
