### ISSUE TITLE
MobileDev Kotlin : Calculator App

### ISSUE THREAD

**Issue by shubhmittal07** [hash-define-organization/Hacktober-Fest-2021#328]
A simple Calculator App which needs some serious UI improvements.
I am contributing this calculator app , but I also want someone to also enhance the UI of this app.

<p align = "left">
<img src ="https://user-images.githubusercontent.com/59731205/137532649-41aff6bd-c117-4b46-99d9-08270d8aac27.png" width="200">
<img src ="https://user-images.githubusercontent.com/59731205/137532789-26f11732-6eeb-46a7-adc1-1dce2669a589.png" width="200">
</p>

**Comment by ij007** [comment]
Assigned 👍🏻
