### ISSUE TITLE
Fix #DEFINE logo in README.md

### ISSUE THREAD

**Issue by budhirajamadhav** [hash-define-organization/Hacktober-Fest-2021#330]
**Is your feature request related to a problem? Please describe.**
During a PR the `readmeSrc` folder was renamed to `resources` and the logo is in that folder, which lead to this:
![image](https://user-images.githubusercontent.com/73742540/137570103-cb485075-9ff0-484d-95f0-9f957cb144e3.png)

**Describe the solution you'd like**
In the [Line 4](https://github.com/hash-define-organization/Hacktober-Fest-2021/blob/master/README.md?plain=1#L4) of the README.md, `readmeSrc` needs to be replaced with `resources`.

**Comment by sarthakgupta878** [comment]
Please assign this issue to me. I will make source path correct so that logo will appear.

Thank you!!

**Comment by XoMute** [comment]
Hi! I've created PR to fix this problem.
I will understand if you won't accept it because this issue is already assigned to another developer,
but since @sarthakgupta878 haven't created a PR yet, maybe you can check mine.
Thanks!
