### ISSUE TITLE
Adding DP problem - Maximal Square 

### ISSUE THREAD

**Issue by vishakha-aggarwal** [hash-define-organization/Hacktober-Fest-2021#47]
I would like to add this problem in a new DP folder in Dsa CPP

### Problem:
Given an m X n binary matrix filled with only 0's and 1's, Find the largest square containing only 1's and return its area.

**Example:**

Let Matrix be:
1,0,1,1,1
1,1,1,1,1
1,0,0,1,0

So, the maximum area of the square would be : 4

Kindly assign me this issue.
Please tag this issue with 'hacktoberfest 2021'.

**Comment by VaibhavPaliwal0007** [comment]
Ok Assigned!!
