### ISSUE TITLE
Finding single element in a sorted array

### ISSUE THREAD

**Issue by vishakha-aggarwal** [hash-define-organization/Hacktober-Fest-2021#52]
I would like to add this problem based on binary search in DSA Cpp folder.

### Problem:
You are given a sorted array where every element appears exactly twice, except for one element which appears exactly once.
Your task is to find that number which is present only once in O(log n) Time complexity and O(1) space complexity. 

**Example:**

arr = [1,1,2,2,3,3,**4**,5,5,6,6]
Hence the output would 4 as it occurs only once.

Kindly assign me this issue for hacktoberfest 2021.

**Comment by VaibhavPaliwal0007** [comment]
Digital Ocean is not accepting DSA spam as few repositories have been banned. Kindly choose a different issue or a relevant one. You can however contribute to another department.
