### ISSUE TITLE
Program to check whether the sentence is pangram

### ISSUE THREAD

**Issue by Tejaswini-052** [hash-define-organization/Hacktober-Fest-2021#53]
Pangram is basically a sentence containing all the letters in the English alphabet!
I would like to add this problem!

**Comment by VaibhavPaliwal0007** [comment]
kindly link the pr to the issue

**Comment by Tejaswini-052** [comment]
> kindly link the pr to the issue

Done!

**Comment by VaibhavPaliwal0007** [comment]
You have link wrong pr to the issue. kindly check!!
