### ISSUE TITLE
Adding Problem - Print all the nodes that are at k distance from the target node.

### ISSUE THREAD

**Issue by vishakha-aggarwal** [hash-define-organization/Hacktober-Fest-2021#54]
I would like to add this tree problem in Dsa CPP folder.

### Problem: 
Given the inorder traversal of the binary tree , value of target node and an integer k, your task is to return an vector of the values of all nodes that are at k distance from the target node.

**Example: **

inorder[] = [6, 5, 7, 2, 4, 3, 0, 1, 8]
target = 5, k = 2

So, the output will be : 7, 4, 1

Kindly assign me this issue for hacktoberfest 2021.

**Comment by VaibhavPaliwal0007** [comment]
Digital Ocean is not accepting DSA spam as few repositories have been banned. Kindly choose a different issue or a relevant one. You can however contribute to another department.
