### ISSUE TITLE
adding code of sudoku solver

### ISSUE THREAD

**Issue by khushijain3103** [hash-define-organization/Hacktober-Fest-2021#56]
I want to add code of sudoku solver using concepts of Backtracking . 

![image](https://user-images.githubusercontent.com/85082142/135652591-61eb6e05-3ff7-4678-878d-fe60dd609528.png)

![image](https://user-images.githubusercontent.com/85082142/135652646-4eb728e1-188a-40cf-a339-d78728c6c738.png)

**Comment by VaibhavPaliwal0007** [comment]
Assigned @khushijain3103!!

**Comment by VaibhavPaliwal0007** [comment]
You need to link the pr to this issue. So I can close this.

**Comment by VaibhavPaliwal0007** [comment]
However, this also violates the Digital Ocean's TOS.
