### ISSUE TITLE
website Front End

### ISSUE THREAD

**Issue by aimassage** [hash-define-organization/Hacktober-Fest-2021#59]
its not that good project because i have just started react and i also not know  how to host web app
adding dev folder in webdev fronte
<img width="950" alt="Capturdsffse" src="https://user-images.githubusercontent.com/90811476/135653891-9a76cd44-7984-433f-aed1-3fb7c5afbe4f.PNG">
nd

**Comment by WINOFFRG** [comment]
It's simple to host a static website on platforms like Github Hosting or Netlify. On can simply google, check the documentation or watch any Youtube video to learn how to host.

**Comment by VaibhavPaliwal0007** [comment]
As there is no response. So closing this issue.
