### ISSUE TITLE
Kinghts Tour Code

### ISSUE THREAD

**Issue by SHIVANGISINGH1** [hash-define-organization/Hacktober-Fest-2021#63]
I would like to add code for Knights Tour done using backtracking.
![image](https://user-images.githubusercontent.com/80265624/135655867-2d504e77-6548-49af-868a-6a4c35790bb4.png)
![image](https://user-images.githubusercontent.com/80265624/135655963-0eb37926-d90f-4e01-a90d-b2b077f65e8c.png)

**Comment by VaibhavPaliwal0007** [comment]
This violates Digital Ocean's TOS.
