### ISSUE TITLE
Netflix clone (html, css)

### ISSUE THREAD

**Issue by yashikakaushik** [hash-define-organization/Hacktober-Fest-2021#83]
I want to add my Netflix-clone project (in html and css).
This is a static website. Here, we can hover and move around to observe features and changes.

Here is a link to my GitHub: https://github.com/yashikakaushik

**Comment by ij007** [comment]
issue closed with PR #149

**Comment by WINOFFRG** [comment]
@yashikakaushik  Your PR has been reverted due to some error from your side. It is requested to create a new PR.
**NOTE: Make sure to remove the `.git` folder from your code.**
