### ISSUE TITLE
➕ Adding questions with code based on binary search algorithm (LeetCode) in CPP

### ISSUE THREAD

**Issue by pratyaksh1610** [hash-define-organization/Hacktober-Fest-2021#99]
I would like to contribute to this issue.

Adding questions with detailed explanation of the code based on binary search algorithm from LeetCode.

1️⃣ https://leetcode.com/problems/search-in-rotated-sorted-array/
2️⃣ https://leetcode.com/problems/split-array-largest-sum/

Pls assign this issue to me.
Thankyou!!

![1a](https://user-images.githubusercontent.com/76740999/135706403-44215081-07bf-40ac-81c5-218d378aa333.png)
![1b](https://user-images.githubusercontent.com/76740999/135706404-e9d105f0-689d-4568-bc91-f1a725751763.png)

**Comment by VaibhavPaliwal0007** [comment]
ok assigned!!! @pratyaksh1610
